### PR TITLE
feat: add mdx component to render light and dark mode image in docs

### PR DESCRIPTION
**Pull request by JessChowdhury**
Add mdx component to render light and dark mode image in docs

### CODE REVIEW

**Comment by jacobsfletch** [comment]
Could we use a media query for this instead? That way the browser doesn't have to download two images? We may be able to use the `picture` element and `srcset` here, unless our dark mode setup isn't compatible, which would be unfortunate. https://dev.to/dailydevtips1/light-and-dark-mode-image-in-html-lji

**Review by jacobsfletch — CHANGES_REQUESTED** [review]
Could we use a media query for this instead? That way the browser doesn't have to download two images? We may be able to use the `picture` element and `srcset` here, unless our dark mode setup isn't compatible, which would be unfortunate. https://dev.to/dailydevtips1/light-and-dark-mode-image-in-html-lji

**Comment by JessChowdhury** [comment]
@jacobsfletch I tried the approach you shared but unfortunately it doesn't respect changes from our light/dark mode toggler, only the overall system preference. 

Instead, I've updated the component to use the existing `useThemePreference()` provider and render the image based on that.

**Comment by jacobsfletch** [comment]
It's likely still going to download both images but I do see your point, media queries in case do not respect _preferred_ theme and so the picture element is not useful.

**Pull request merged**
